-- =====================================================================
-- Y&Y PLASTIC · Pedidos con retiro en tienda + sesiones de admin
-- (aplicado en Supabase como migraciones yyplastic_09 / 10 / 11)
-- =====================================================================
-- Resumen de lo creado:
--  * yyplastic_sesiones: tokens de sesión del admin (180 días). check_password
--    acepta la clave o un token "yyt_...". Funciones: yyplastic_login,
--    yyplastic_logout, yyplastic_cambiar_clave_sesion (cierra las demás sesiones).
--  * yyplastic_pedidos / yyplastic_pedido_items (sin políticas RLS: privados).
--    Folio correlativo desde 1001 y codigo_seguimiento secreto para el cliente.
--    Campos listos para pasarela: metodo_pago ('en_tienda'|'online'),
--    estado_pago, pago_proveedor, pago_referencia, pago_fecha.
--  * yyplastic_crear_pedido(cliente, items, metodo_pago): calcula precios en el
--    servidor (precio al mayor automático desde minimo_mayor).
--  * yyplastic_ver_pedido(codigo): seguimiento público con el código.
--  * yyplastic_admin_pedidos / yyplastic_actualizar_pedido: panel del dueño.
--  * Trigger yyplastic_pedidos_aviso -> realtime.send(..., 'yyplastic-pedidos', false)
--    con solo id/folio; el panel admin trae el detalle con su token.
--  * Config: pago_online_activo ('no' por ahora), retiro_direccion, retiro_instrucciones.
--
-- PENDIENTE para la pasarela (Flow / Webpay / Mercado Pago):
--  1. Función servidor (Cloudflare Pages Function o Supabase Edge Function) que cree
--     la transacción con la clave secreta del proveedor y devuelva la URL de pago.
--  2. Webhook del proveedor -> actualiza estado_pago/pago_referencia usando la
--     service_role key (nunca desde el navegador).
--  3. Poner pago_online_activo = 'si' para mostrar la opción en el carrito.

-- =====================================================================
-- ACTUALIZACIÓN (migraciones yyplastic_12 a 16)
-- =====================================================================
--  * Pago con Flow ACTIVO (config pago_online_activo = 'si'). Las claves viven cifradas
--    en el vault de Supabase (yyplastic_flow_api_key / yyplastic_flow_secret_key), nunca en la web ni en GitHub.
--  * Edge Function "yyplastic-flow" (sin JWT; valida con Flow):
--      POST /crear      -> crea el cobro en Flow y devuelve la URL de pago
--      POST /confirmar  -> Flow avisa servidor a servidor; se consulta a Flow y se registra
--      POST /retorno    -> el cliente vuelve de Flow; se registra y redirige a
--                          https://y-y-plastic.pages.dev/?pedido=<codigo>&pago=<estado>
--    Dominios permitidos (CORS/retorno): ver SITIOS en la función.
--  * Funciones solo para el servidor (service_role): yyplastic_flow_credenciales, yyplastic_pedido_para_pago,
--    yyplastic_pedido_guardar_token, yyplastic_pago_registrar (verifica que el monto pagado = total del pedido).
--  * Pedidos: cliente_rut (validado con módulo 11), pago_token, pago_medio.
--  * Productos: unidad_mayor y descripcion_mayor (presentación/descripción propias del precio al mayor)
--    y stock (int >= 0, por ahora solo informativo).
--  * El pedido guarda la presentación que corresponde al precio cobrado (detalle o mayor).

-- =====================================================================
-- STOCK, CAJAS Y PAGO SOLO CON FLOW (migraciones yyplastic_17 y 18)
-- =====================================================================
--  * El pago es siempre con Flow (retiro en tienda). yyplastic_crear_pedido rechaza cualquier otro método.
--  * Stock en UNIDADES (las del detalle). productos.unidades_por_caja: cuántas unidades trae una caja.
--      - Al detalle se compra por unidad; al mayor por CAJA (1 caja = unidades_por_caja unidades de stock).
--      - minimo_mayor = mínimo de cajas; precio_mayor = precio por caja.
--  * Cada línea del pedido: {producto_id, tipo: 'detalle'|'mayor', cantidad}. El servidor valida el stock y lo
--    descuenta en el mismo momento (sin sobreventa). pedido_items.unidades guarda lo descontado.
--  * El stock vuelve si el dueño cancela el pedido (yyplastic_actualizar_pedido) y se descuenta de nuevo si lo reactiva.
--  * pg_cron 'yyplastic-liberar-pedidos' (cada 10 min): pedidos online sin pagar tras 60 min se cancelan y devuelven el stock.
--  * Si Flow confirma un pago de un pedido ya cancelado por tiempo, se reactiva y se vuelve a reservar el stock.
--  * El formulario del producto solo envía "stock" si el dueño lo cambió (no pisa ventas hechas mientras editaba).
--  * Ayudantes internos en el esquema private (no expuesto a la web): devolver_stock, reservar_stock, liberar_pedidos_vencidos.
--  * pedidos.eliminado: los pedidos "eliminados" no salen en el panel ni en el seguimiento (el conector no permite DELETE).
--
-- Para borrar DEFINITIVAMENTE los pedidos y productos de prueba (ejecutar en el SQL Editor) y reiniciar el folio:
--   delete from public.yyplastic_pedido_items where pedido_id in (select id from public.yyplastic_pedidos where eliminado);
--   delete from public.yyplastic_pedidos where eliminado;
--   delete from public.yyplastic_productos where eliminado and nombre like 'TEST%';
--   select setval('public.yyplastic_pedido_folio_seq', 1000, true);
